### ISSUE TITLE
GetPaymentMethods fails with GDAX exception: invalid signature

### ISSUE THREAD

**Issue by Grepsy** [ChristopherHaws/gdax-dotnet#8]
`GetProductTicker` does work as expected. I've doubled checked my key, passphrase and secret and have all the permissions set. Any idea what might cause this?

`GetAccounts` is also failing.

I'm not using the Sandbox.

**Comment by sergiomcalzada** [comment]
All secured call are failling :(

**Comment by ChristopherHaws** [comment]
GDAX must have made changes regarding permissions for the APIs. It appears your API key now need the `Transfer` permission to call `GetPaymentMethods`, however there is an issue with deserialization. It appears the contract for this method has changed. I will take a look at it later tonight.

As for `GetAccounts` failing; it seems to be working fine on my end. What error are you getting?

**Comment by sergiomcalzada** [comment]
I have a key with full permissions and none of the secured calls are working. I will regenerate the key and test again later. The error is 'invalid signature'

**Comment by sergiomcalzada** [comment]
I regenerated the API Key and I'm still getting "invalid signature" error 😢

**Comment by sergiomcalzada** [comment]
Fixed invalid signature erros, got pull request https://github.com/ChristopherHaws/gdax-dotnet/pull/9

**Comment by Grepsy** [comment]
Great, that fixed it!
